"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { getProjectDetail } from "@/lib/api";
import StatusIndicator from "@/components/projects/StatusIndicator";
import SourceBadge from "@/components/projects/SourceBadge";
import { MapPin, Calendar, IndianRupee, Building2, HardHat, TrendingUp, AlertCircle, Bot } from "lucide-react";

export default function ProjectDetailPage() {
  const params = useParams();
  const [project, setProject] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function loadProject() {
      try {
        const data = await getProjectDetail(params.id as string);
        setProject(data);
      } catch (err: any) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    }
    if (params.id) {
      loadProject();
    }
  }, [params.id]);

  if (loading) return <div className="p-8 text-center">Loading project details...</div>;
  if (error) return <div className="p-8 text-center text-red-600">Error: {error}</div>;
  if (!project) return <div className="p-8 text-center">Project not found.</div>;

  return (
    <div className="max-w-5xl mx-auto p-4 md:p-8">
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-2">
          <StatusIndicator status={project.status} />
          {project.is_verified && (
            <span className="inline-flex items-center gap-1 text-xs font-medium text-emerald-700 bg-emerald-50 px-2.5 py-0.5 rounded-full border border-emerald-200">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-500"></span> Verified Data
            </span>
          )}
        </div>
        <h1 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">{project.name}</h1>
        
        <div className="flex flex-wrap gap-4 text-sm text-gray-600">
          <div className="flex items-center gap-1.5"><MapPin className="w-4 h-4" /> {project.city}{project.district ? `, ${project.district}` : ''}</div>
          <div className="flex items-center gap-1.5"><Building2 className="w-4 h-4" /> {project.authority || "Unknown Authority"}</div>
          <div className="flex items-center gap-1.5 capitalize"><HardHat className="w-4 h-4" /> {project.project_type.replace('_', ' ')}</div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        {/* Main Content */}
        <div className="md:col-span-2 space-y-8">
          
          {/* AI Summary Section */}
          {project.ai_summary ? (
            <div className="bg-gradient-to-br from-indigo-50 to-blue-50 rounded-xl p-6 border border-indigo-100 shadow-sm relative overflow-hidden">
              <div className="absolute top-0 right-0 p-4 opacity-10">
                <Bot className="w-24 h-24" />
              </div>
              <h2 className="text-xl font-bold text-indigo-900 mb-4 flex items-center gap-2">
                <Bot className="w-5 h-5" /> AI Intelligence Summary
              </h2>
              
              <div className="space-y-4 relative z-10">
                <div>
                  <h3 className="font-semibold text-indigo-800 text-sm mb-1">What is being built?</h3>
                  <p className="text-gray-700 text-sm leading-relaxed">{project.ai_summary.what_is_being_built}</p>
                </div>
                <div>
                  <h3 className="font-semibold text-indigo-800 text-sm mb-1">Why it matters</h3>
                  <p className="text-gray-700 text-sm leading-relaxed">{project.ai_summary.why_it_matters}</p>
                </div>
                <div>
                  <h3 className="font-semibold text-indigo-800 text-sm mb-1">Expected Impact</h3>
                  <p className="text-gray-700 text-sm leading-relaxed">{project.ai_summary.expected_impact}</p>
                </div>
                <div>
                  <h3 className="font-semibold text-indigo-800 text-sm mb-1">Benefiting Areas</h3>
                  <p className="text-gray-700 text-sm leading-relaxed">{project.ai_summary.nearby_benefiting_areas}</p>
                </div>
              </div>
              <div className="mt-4 pt-4 border-t border-indigo-100 flex justify-between items-center text-xs text-indigo-400">
                <span>Generated by {project.ai_summary.model_used || "AI Model"}</span>
                <span>{new Date(project.ai_summary.generated_at).toLocaleDateString()}</span>
              </div>
            </div>
          ) : (
            <div className="bg-gray-50 rounded-xl p-6 border border-gray-200 text-center">
              <AlertCircle className="w-8 h-8 text-gray-400 mx-auto mb-2" />
              <p className="text-gray-500 text-sm">AI Summary generation is queued for this project.</p>
            </div>
          )}

          {/* Official Description */}
          <div>
            <h2 className="text-xl font-bold text-gray-900 mb-4">Official Description</h2>
            <div className="prose prose-sm max-w-none text-gray-600">
              {project.description ? (
                <p>{project.description}</p>
              ) : (
                <p className="italic text-gray-400">No official description provided.</p>
              )}
            </div>
          </div>

          {/* Verified Sources */}
          <div>
            <h2 className="text-xl font-bold text-gray-900 mb-4">Verified Sources</h2>
            {project.sources && project.sources.length > 0 ? (
              <div className="flex flex-wrap gap-3">
                {project.sources.map((source: any) => (
                  <SourceBadge 
                    key={source.id} 
                    sourceType={source.source_type}
                    title={source.title}
                    url={source.url}
                    authorityName={source.authority_name}
                  />
                ))}
              </div>
            ) : (
              <p className="text-sm text-gray-500 italic">No public sources verified yet.</p>
            )}
          </div>
        </div>

        {/* Sidebar */}
        <div className="space-y-6">
          {/* Key Metrics */}
          <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-5">
            <h3 className="font-bold text-gray-900 mb-4">Key Metrics</h3>
            <div className="space-y-4">
              <div className="flex items-start gap-3">
                <div className="p-2 bg-emerald-50 rounded-lg text-emerald-600"><IndianRupee className="w-5 h-5" /></div>
                <div>
                  <p className="text-xs text-gray-500 uppercase tracking-wider">Estimated Budget</p>
                  <p className="font-semibold text-gray-900">{project.budget_crore ? `₹${project.budget_crore} Crore` : 'Undisclosed'}</p>
                </div>
              </div>
              <div className="flex items-start gap-3">
                <div className="p-2 bg-blue-50 rounded-lg text-blue-600"><Calendar className="w-5 h-5" /></div>
                <div>
                  <p className="text-xs text-gray-500 uppercase tracking-wider">Expected Completion</p>
                  <p className="font-semibold text-gray-900">{project.expected_completion ? new Date(project.expected_completion).toLocaleDateString() : 'TBD'}</p>
                </div>
              </div>
              <div className="flex items-start gap-3">
                <div className="p-2 bg-purple-50 rounded-lg text-purple-600"><TrendingUp className="w-5 h-5" /></div>
                <div>
                  <p className="text-xs text-gray-500 uppercase tracking-wider">Impact Radius</p>
                  <p className="font-semibold text-gray-900">{project.impact_radius_km ? `${project.impact_radius_km} km` : 'N/A'}</p>
                </div>
              </div>
            </div>
          </div>

          {/* Map Preview Placeholder */}
          <div className="bg-gray-100 rounded-xl border border-gray-200 h-48 flex flex-col items-center justify-center text-gray-500 overflow-hidden relative">
            {project.latitude && project.longitude ? (
               <div className="absolute inset-0 bg-[url('https://a.tile.openstreetmap.org/11/1460/860.png')] bg-cover bg-center opacity-50"></div>
            ) : null}
            <MapPin className="w-8 h-8 mb-2 relative z-10" />
            <span className="text-sm font-medium relative z-10">Map View Available</span>
            <a href={`/map?project_id=${project.id}`} className="mt-2 text-xs text-blue-600 font-semibold relative z-10 hover:underline">Open in Interactive Map →</a>
          </div>
        </div>
      </div>
    </div>
  );
}
