"""add_distress_properties

Revision ID: 3c3c3e78704b
Revises: a01c4ef7eac1
Create Date: 2026-06-18 20:10:00.310901
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '3c3c3e78704b'
down_revision: Union[str, None] = 'a01c4ef7eac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distress_properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('property_type', sa.String(length=100), nullable=False),
    sa.Column('market_value', sa.Float(), nullable=False),
    sa.Column('reserve_price', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('auction_date', sa.String(length=100), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_areas_centroid', 'areas', ['centroid'], unique=False, postgresql_using='gist')
    op.create_index('ix_projects_location', 'projects', ['location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_projects_location', table_name='projects', postgresql_using='gist')
    op.drop_index('ix_areas_centroid', table_name='areas', postgresql_using='gist')
    op.drop_table('distress_properties')
    # ### end Alembic commands ###
