"""add_backing_authority_to_distress

Revision ID: 8ee92c423a76
Revises: cccb57ea35a2
Create Date: 2026-06-19 18:01:58.990349
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '8ee92c423a76'
down_revision: Union[str, None] = 'cccb57ea35a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distress_properties', sa.Column('backing_authority', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distress_properties', 'backing_authority')
    # ### end Alembic commands ###
